### ISSUE TITLE
{{#tests?}} - the ?

### ISSUE THREAD

**Issue by ghost** [zombor/KOstache#1]
mustache spec doesn't say anything about how to determine non-empty list. and its author denied to add this syntax to spec (defunkt/mustache#47) and left this task to view.

in my test, the test? section is rendered as nothing. i thought it would be overloading the __isset and __get in view and using kind of {{#has_tests}} or any better solution?

**Comment by shadowhand** [comment]
A non-empty list test is `{{^list}}`.
