### ISSUE TITLE
Templating and View-Model separation

### ISSUE THREAD

**Issue by lukemorton** [zombor/KOstache#10]
I think a long term goal should probably be the separation of templates and the view class. This would allow the changing of template engines without needing to affect the View-Model, for example you could swap out the Mustache engine for JSON.

This might be out of the scope of Kostache however.

**Comment by shadowhand** [comment]
This is outside the scope of Kostache, but it has been discussed among the Kohana devs.

**Comment by zombor** [comment]
Yeah, Kostache will likely always be tied, but look for a different project at some point to "generalize" view models.
