### ISSUE TITLE
Method to assign literal partials

### ISSUE THREAD

**Issue by czukowski** [zombor/KOstache#12]
KOstache now exposes public method to load partials by providing path to them. It would be nice to be able to do the same, but for literal partials (i.e. that were generated dynamically).

I've had such method in my application code, incidentally named `partial`, which can't work after recent KOstache update, so I'm thinking of adding it back with another name, if you wouldn't have a better idea.

**Comment by czukowski** [comment]
What do you think about this? Too much of possible unnecessary strain on `Kohana::find_file()` or reasonable solution?

```
public function partial($name, $path)
{
    if ( ! $path)
    {
        unset($this->_partials[$name]);
    }
    else
    {
        try
        {
            $this->_partials[$name] = $this->_load($path);
        }
        catch (Kohana_Exception $e)
        {
            // Add partial literally
            $this->_partials[$name] = $path;
        }
    }

    return $this;
}
```

**Comment by shadowhand** [comment]
See #15.
