### ISSUE TITLE
Kostache_Layout $template should default to $_layout not _detect_template()

### ISSUE THREAD

**Issue by nickolasgregory** [zombor/KOstache#16]
For example; I have

```
class View_Layout_Default extends Kostache_Layout {
    protected $_layout = 'layout/default';
}

class View_Layout_News extends View_Layout_Default {
    /* ..etc.. */
}
```

Because Kostache uses __detect_template()_ to construct the view I cannot instantiate View_Layout_News without having an **empty** template file _layout/news.mustache_

I think _Kohana_Kostache_Layout_ needs a constructor:

```
public function __construct($template = NULL, array $partials = NULL)
{
    if ( ! $template)
    {
        $template = $this->_layout;
    }

    parent::__construct($template, $partials);
}
```

(but I could be wrong.)

**Comment by shadowhand** [comment]
Read the source, this issue is totally invalid. You are not supposed to name your views `View_Layout_Foo` just because they extend `View_Layout`. What your name your view directly correlates with the template path.

**Comment by nickolasgregory** [comment]
I'm not talking about naming my class, it just happens that the template/layout path is '_layout/default_' and it's not using the _content_ partial.

_View_Layout_News_ uses the inherited, **$_layout**

ie; I don't want to create a template '_layout/news.mustache_' - it will never be used.

I can't instantiate View_Layout_News without an empty _mustache_ file, which seems a bit silly.

**Comment by shadowhand** [comment]
Your class naming has everything to do with this... what you name your class reflects the template that will be loaded. Why are you naming something `View_Layout_Foo` if it is not an abstract layout class? If it is an actual view class, then do not put "Layout" in the name.

If you are attempting to use a "Layout" class without `{{content}}`, you are doing it wrong. It sounds to me like your class should be `View_News extends View_Layout`.

**Comment by nickolasgregory** [comment]
The penny has dropped.

I'd been trying to load a view based on a 'layout' (the html/head/body stuff) and not the template that goes into the layout's <code>{{>content}}</code>. (back-to-front as it were.)

Doing it the right way cleanups up a few other things for me too.

Thanks for your replay (and your persistence.)
