### ISSUE TITLE
Change Kostache_Layout::CONTENT_PARTIAL from 'content'

### ISSUE THREAD

**Issue by nickolasgregory** [zombor/KOstache#17]
One of my views already had a partial called '_content_' obviously clashing with the new;

```
const CONTENT_PARTIAL = 'content';
```

After updating to Kostache 2 my working view blew up (somewhere in a Mustache regex?) and debugging was tricky, until the light went on.

Maybe a value less likely to clash with or be used by another coder (ie; me) could be considered.

**Comment by lukemorton** [comment]
The idea of having this stored in a constant allows you to update the value yourself (in a child class). Kostache references Kostache_Layout::CONTENT_PARTIAL not Kohana_Kostache_Layout::CONTENT_PARTIAL, thus you can make your own Kostache_Layout and define the CONTENT_PARTIAL to anything you desire.

**Comment by nickolasgregory** [comment]
True, thanks @DrPheltRight. (nice blog BTW.)

Perhaps it's just a documentation issue / something to be aware of.

**Comment by lukemorton** [comment]
No problems (and thanks).

I don't disagree with you there.
