### ISSUE TITLE
Partials inheritance?

### ISSUE THREAD

**Issue by nanodocumet** [zombor/KOstache#23]
I know there is the variable $_partials that holds the partials for the template, which could be overwritten by extended classes. And I know there is also a partial() method that allows to set partials. However, it will be nice if we could have a way to inherent some partials from a base view and overwrite just some of them in a child view.

Example:

```
class View_Site extends Kostache {

protected $_template = 'site';

protected $_partials = array(
    'header'  => 'partials/sections/header',
    'banner'  => 'partials/sections/banner',
    'contents' => 'partials/templates/2cols',
    'footer'  => 'partials/sections/footer',
    );
    ...
 }

class View_Homepage extends View_Site {

protected $_local_partials = array(
    'banner'  => 'partials/sections/homepage/banner',
    'contents' => 'partials/templates/3cols',
    // Partials specific to new content
    'column1' => 'partials/sections/homepage/col1',
    'column2' => 'partials/sections/homepage/col2',
    'column3' => 'partials/sections/homepage/col3',
    );
    ...
 }

 // Then at Kostache
abstract class Kohana_Kostache {
...
    if ($this->_partials)
    {
        // Merge locals with partials
        $this->_partials = Arr::merge($this->_partials, $this->_local_partials);

        foreach ($this->_partials as $name => $path)
        {
                ...
  }
```

With this, My Homepage will use View_Site as the base View, using the "site" template and using the default partials; and then "overwrite" only the ones that are different (In this case from a default 2 columns to a custom 3 columns and using a different banner). I know I can achieve the same by doing: 

```
class View_Homepage extends View_Site {

protected $_partials = array(
    'header'  => 'partials/sections/header',
    'banner'  => 'partials/sections/banner_homepage',
    'contents' => 'templates/3cols',
    'footer'  => 'partials/sections/footer',
    // Partials specific to new content
    'column1' => 'partials/sections/homepage/col1',
    'column2' => 'partials/sections/homepage/col2',
    'column3' => 'partials/sections/homepage/col3',
    );
    ...
 }
```

or by overloading the construct and setting my partials via the partial() method, but I find the former way not so DRY (if I want to change the partial path for the header, I will just need to update the base View_Site and all children views will reflect the change immediately, in contrast the current way will need to change all the children as well) and the latter too verbose. I think, allowing some type of inheritance will be nice.

I also know there is a Kostache_Layout class that allows some kind of overloading of partials, but IMHO I find it not so flexible and somehow limited.

Food for thought :). Good night.

thanks.

**Comment by shadowhand** [comment]
This is not going to happen. Overload the view `__construct` method if you want to add additional partials.
