### ISSUE TITLE
View_Layout

### ISSUE THREAD

**Issue by iammerrick** [zombor/KOstache#24]
Doesn't exist as the README guides, it should be changed to Kostache_Layout

**Comment by iammerrick** [comment]
Or perhaps make it known that it should be extended like so:

View_Layout extends Kostache_Layout.

**Comment by mahonnaise** [comment]
README.markdown still refers to View_Layout (in that section at the bottom titled "Using the View_Layout class") though.

**Comment by shadowhand** [comment]
@mahonnaise Please create a new pull request or issue.

**Comment by zombor** [comment]
This is already fixed in develop.
