### ISSUE TITLE
exception_handler no longer used.

### ISSUE THREAD

**Issue by ghost** [zombor/KOstache#26]
On line 118 of the kostache core class

```
Kohana::exception_handler($e);
```

Should be

```
Kohana_Exception::handler($e);
```

no?

**Comment by shadowhand** [comment]
The former is correct for 3.0 versions, and the latter is [already in place](https://github.com/zombor/KOstache/blob/3.1%2Fmaster/classes/kohana/kostache.php#L114) for 3.1+.

**Comment by ghost** [comment]
My mistake =)

Thanks
