### ISSUE TITLE
Kohana::find_file error in partials

### ISSUE THREAD

**Issue by Neurergus** [zombor/KOstache#3]
Hi,

First, I don't know if it's an issue or something I'm doing wrong, but here it is. I'm using the latest master branch of Kostache.

I have this controller action:

```
public function action_modify($model_id)
{
    $model = Jelly::query('model', $model_id)->select();

    $view = Kostache::factory('model/modify');
        $view->set('model', $model);

    if ($_POST)
    {
        /* Etc */
    }

    $this->request->response = $view;
}
```

And the views:

```
View_Model_Modify extends View_Model_Insert { ... }
View_Model_Insert extends View_General_Base { ... }
View_General_Base extends View_Layout { ... }
```

The templates doesn't have anything special, and the "layout.mustache" has the {{>body}} part.

Summary: using kostache's layout view.

Here's the problem, with this particular action and template (modify) I get this error:

```
ErrorException [ Warning ]: is_file(): open_basedir restriction in effect. File(/server/htdocs/XXX/admin/application/templates/ <div id="formulario_w"> MUCH MORE HTML & Mustache </div> .mustache) is not within the allowed path(s): (/server/:/home/:/tmp/:/usr/share/pear/)
```

After seeing that, I modified the Kostache render function:

```
    // Convert partials to expanded template strings
    foreach ($this->_partials as $key => $partial_template)
    {
        Kohana::$log->add('INFO', 'PARTIAL TEMPLATE: '.var_export($partial_template, TRUE));

        if ($location = Kohana::find_file('templates', $partial_template, 'mustache'))
        {
            $this->_partials[$key] = file_get_contents($location);
        }
    }
```

In all cases, even when there's no error, $partial_template has the content of the mustache file. The only thing different with the modify template is that it's somewhat larger than the others, and maybe has something like "../" or similar, hence the open_basedir error.

I suppose that $partial_template should contain the name of the template, not the content.

Am I doing something wrong?

Update: apart from {{>body}}, I'm not using partials.

**Comment by zombor** [comment]
Try this branch: http://github.com/zombor/KOstache/tree/release/1.2

**Comment by Neurergus** [comment]
It works.

Thank you :-)
