### ISSUE TITLE
Adding mustache as a submodule

### ISSUE THREAD

**Issue by ghost** [zombor/KOstache#33]
Isn't is possible to add mustache as a submodule so that when you add KOstache as a submodule to your project mustache gets added as well? I'm new to git, so I might be missing something. I'm not really sure what's the best way to add mustache in the vendor library?

**Comment by nexeck** [comment]
mustache is a submodule, within the vendor directory.
If you add a submodule with git, you have to update the submodules within this submodule yourself.

**Comment by ghost** [comment]
Thanks

**Comment by shadowhand** [comment]
`git submodule update --init --recursive` from the top level of the project will update all submodules, all the way down.

**Comment by ghost** [comment]
Thanks for the tip shadowhand. I'll make a pull request to change the userguide to reflect this. Who knows, it might help others.

**Comment by sineld** [comment]
Thanks for the tip shadow hand I was wondering how to do it.
