### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by AlanHee** [zombor/KOstache#37]
Fatal error: Class 'Kohana_Mustache' not found in /www/kohanaphp/modules/kostache/classes/kohana/kostache.php on line 226

**Comment by zombor** [comment]
Not sure what's going on. It's right here: https://github.com/zombor/KOstache/blob/master/classes/kohana/mustache.php

**Comment by shadowhand** [comment]
You could get that error if you don't run `git submodule update --init --recursive` after the first installation.

**Comment by AlanHee** [comment]
aha, its my mistake

**Comment by AlanHee** [comment]
thanks a lot!
