### ISSUE TITLE
Partials should be able to have a view class

### ISSUE THREAD

**Issue by rjd22** [zombor/KOstache#38]
Shouldn't partials have their own view class when needed? Like I have a sidebar as a partial. I want to generate some dropdowns for it. Now I have to put my view code in the head view class while it actually should be in an sidebar.php view class.

Please correct me if I'm wrong.

**Comment by zombor** [comment]
By definition of the mustache spec, no. If you want it in it's own view class, you need to instantiate that view class and render it into a template variable. I usually put layout code inside my layout view, and extend from there.
