### ISSUE TITLE
Templates Directory

### ISSUE THREAD

**Issue by miket3** [zombor/KOstache#4]
KOstache assumes your templates will be withiin reach of the cascading file system. However Kohana::file_find() is not recursive so you need to be careful not to place your templates directory too deep outside the reach of the cascading file system. This isnt necessarily an issue with KOstache, but more of a gotcha between KO3 and KOstache.

**Comment by zombor** [comment]
What does this even mean? It works the same as any other asset in kohana, be it a class, configuration file, , or plain old view file. There's no problem here.

Again, _please_ read about the cascading file system in kohana: http://kohanaframework.org/guide/about.filesystem

**Comment by miket3** [comment]
It means exactly what I said.    My original structure was application/views/templates/example.mustache   and kohana could not find the template by default.  Which means Kohana::find_file()  does not reach/look below application/views.  As soon as I moved example.mustache into application/templates/example.php it ran like a champ.

**Comment by miket3** [comment]
I came at this as a total beginner.  So, when you just copy directories, and try to run it, it runs fine.  But if you dont want your templates in the modules directory which is where they are by default in the example, then an issue arises. Beginners are always looking for direction and best practices.  If I am wrong about keeping the templates in the module directory then please correct me. But I just assumed it was better practice to keep the templates under the application/views directory.

**Comment by zombor** [comment]
No, your templates go in the templates/ directory in the cascading filesystem. For your application, that would be APPPATH.'templates/' and for a module it would be MODPATH.$modname.'templates/'

They don't go in the views folder at all.
