### ISSUE TITLE
Layout.mustache instead of layout.mustache

### ISSUE THREAD

**Issue by mickrip** [zombor/KOstache#46]
Typical Kostache viewmodels have capitalised separators. ie. View_Page. It'd be more consistent if the default layout template be Layout.mustache (instead of lowercase) to match the typical naming of the other templates.

**Comment by zombor** [comment]
I don't think I agree with this. Kohana's normal views are also lower case. PSR-0 only applies to classes.

**Comment by creatoro** [comment]
@zombor: I think you should sitck to lowercase as well.

But to make sure this works _always_, then it would be necessary to make the filename lowercase in the `_load_file` method:

```
protected function _load_file($name)
{
    $filename = Kohana::find_file($this->_base_dir, strtolower($name), $this->_extension);
    return file_get_contents($filename);
}
```

If it's not converted to lowercase on some systems the file is not found, because of the new, PSR-0 file names...

**Comment by zombor** [comment]
Can you file a new issue for that? A PR would be nice too :)
