### ISSUE TITLE
Issue with PSR-0 file naming and template file names.

### ISSUE THREAD

**Issue by creatoro** [zombor/KOstache#47]
Under Kohana 3.3 the template files are loaded according to PSR-0 naming conventions. For example the file 'about/contact.mustache' would be loaded as 'About/Contact.mustache'.

Some systems would look for these files case-sensitive, so they are not found if not properly named.

Change needed to the `_load_file` method to always look for lowercase template file names.

**Comment by zombor** [comment]
Merged, thanks.
