### ISSUE TITLE
Composer & Packagist support

### ISSUE THREAD

**Issue by anroots** [zombor/KOstache#52]
Task / Feature request:

Add [composer.json](http://getcomposer.org) and submit the module to [packagist.org](http://packagist.org) - for easier inclusion in Composer-powered Kohana projects.

**Comment by cmwelsh** [comment]
+1 for this. Mustache.php supports Composer already so this would also remove the need for a submodule (it can be handled with a Composer dependency) and remove the need to manually load Mustache at all.

**Comment by zombor** [comment]
I'd like to support both git submodule usage, as well as composer (I won't sacrifice the former for the latter).

**Comment by cmwelsh** [comment]
I have a patch planned to fix this. I will re open my pull request soon.

On Tuesday, January 29, 2013, Jeremy Bush wrote:

> I'd like to support both git submodule usage, as well as composer (I won't
> sacrifice the former for the latter).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zombor/KOstache/issues/52#issuecomment-12839119.

## 

Sent from my phone

**Comment by samwilson** [comment]
+1

**Comment by shadowhand** [comment]
Fixed by #69.
