### ISSUE TITLE
Tabs from parent template get passed into the return of a lamba in an included partial

### ISSUE THREAD

**Issue by davecarlson** [zombor/KOstache#64]
VERY odd bug:

we have this lamba function in our view class: 

``` php
public function __()
{
    return function($string)
    {
        return __($string);
    };
}
```

that is called in the mustache via: 

``` mustache
{{#__}}string_to_replace{{/__}}
```

__() is an internal function to get a translation of a string. 

if it is called inside a partial, if there is a tab character before the {{>partial}}, then on each eval of the lamba, it adds the tab characters into the result.
ensuring {{>partial}} starts at the first character 'fixes' it, but it's a very odd bug. for reference, calling my lamba on the parent does not cause this error.

**Comment by zombor** [comment]
This probably pertains to mustache.php, not kostache.

**Comment by davecarlson** [comment]
excellent news! out of curiosity, do you understand the problem ?
