### ISSUE TITLE
$_partials and $_template should be named $_partial_paths and $_template_path

### ISSUE THREAD

**Issue by zeelot** [zombor/KOstache#9]
We should not be mixing paths and content, it leads to hard to find bugs and confusing properties. The following seems like a much simpler approach:

```
protected $_partials = array(
    'foo' => '{{#foo}}{{name}}{{/foo}}',
);
protected $_partial_paths = array(
    'bar' => 'some/path/to/partial','
);
```

I can submit a pull request soonish.

**Comment by shadowhand** [comment]
New branches 3.0/not-extends-mustache and 3.1/not-extends-mustache invalidate this issue.

**Comment by zeelot** [comment]
maybe I was a little confused a few days ago when we discussed it on irc but v2.0 still does this... you are storing paths in _partials and then replacing it with the template content... seems quite silly and confusing even though it's a much less important issue now that it only happens once

**Comment by shadowhand** [comment]
I guess we could use a more verbose name, but what difference does it make? Kostache no longer extends Mustache, so it doesn't matter either way.

**Comment by zombor** [comment]
I really consider this a non-issue. Nobody is confused here.

**Comment by zeelot** [comment]
Personally I find the fact that you are putting things into `_partials` that are not partials to be very confusing. If you hate typing extra characters you could just call it `_paths`. But I won't argue for this any more, it seems like I just can't convince you that changing the type of values stored in a variable at some arbitrary point in code is a bad idea and implementing this in my fork will only be a couple lines of difference so it's not a big deal.

As for the difference it makes... the fact that I cannot put a partial in my class' `_partials` property without an exception being thrown seems weird (from what I could tell from skimming the code). But really even if there were no limitations, the thing bothering me here is the needless reuse of a property that I was never able to understand the reasoning for.

**Comment by shadowhand** [comment]
Actually having anything except for paths in a view is a minority corner case, imo. The entire point of decoupling Kostache from Mustache was so that kind of ambiguous "maybe the partial is already loaded" crap would cease to be an issue, and now you are asking for us to support again.

The answer to this issue is: everything in your view class is referenced by path, period.
